#!/usr/bin/env python3.13
"""
Calculator MCP Server
Provides basic arithmetic operations (add, subtract, multiply, divide) as MCP tools

Generated by Context Foundry
"""
import sys
import json
from typing import Optional

try:
    from fastmcp import FastMCP
except ImportError:
    print("❌ Error: FastMCP not installed", file=sys.stderr)
    print("", file=sys.stderr)
    print("Install with: pip install fastmcp>=2.0.0", file=sys.stderr)
    sys.exit(1)

# Create MCP server instance
mcp = FastMCP("Calculator MCP Server")


# ============================================================================
# CALCULATOR TOOLS - Basic arithmetic operations
# ============================================================================

# Define the actual calculation functions (testable)
def _add(a: float, b: float) -> str:
    """
    Add two numbers together.

    This tool performs addition of two numbers and returns the sum.
    Supports integers, floating-point numbers, and negative numbers.

    Args:
        a: First number to add
        b: Second number to add

    Returns:
        JSON string containing the operation details and result
    """
    try:
        result = a + b
        return json.dumps({
            "operation": "add",
            "a": a,
            "b": b,
            "result": result
        }, indent=2)
    except Exception as e:
        return json.dumps({"error": str(e)}, indent=2)


def _subtract(a: float, b: float) -> str:
    """
    Subtract the second number from the first.

    This tool performs subtraction (a - b) and returns the difference.
    Supports integers, floating-point numbers, and negative numbers.

    Args:
        a: First number (minuend)
        b: Second number to subtract (subtrahend)

    Returns:
        JSON string containing the operation details and result
    """
    try:
        result = a - b
        return json.dumps({
            "operation": "subtract",
            "a": a,
            "b": b,
            "result": result
        }, indent=2)
    except Exception as e:
        return json.dumps({"error": str(e)}, indent=2)


def _multiply(a: float, b: float) -> str:
    """
    Multiply two numbers together.

    This tool performs multiplication of two numbers and returns the product.
    Supports integers, floating-point numbers, and negative numbers.

    Args:
        a: First number to multiply
        b: Second number to multiply

    Returns:
        JSON string containing the operation details and result
    """
    try:
        result = a * b
        return json.dumps({
            "operation": "multiply",
            "a": a,
            "b": b,
            "result": result
        }, indent=2)
    except Exception as e:
        return json.dumps({"error": str(e)}, indent=2)


def _divide(a: float, b: float) -> str:
    """
    Divide the first number by the second.

    This tool performs division (a / b) and returns the quotient.
    Includes proper handling for division by zero, returning an error
    instead of crashing. Supports integers, floating-point numbers, and
    negative numbers.

    Args:
        a: Numerator (number to be divided)
        b: Denominator (number to divide by)

    Returns:
        JSON string containing the operation details and result, or error
        if division by zero is attempted
    """
    try:
        if b == 0:
            return json.dumps({"error": "Cannot divide by zero"}, indent=2)

        result = a / b
        return json.dumps({
            "operation": "divide",
            "a": a,
            "b": b,
            "result": result
        }, indent=2)
    except Exception as e:
        return json.dumps({"error": str(e)}, indent=2)


# Register the tools with MCP (wrapping the functions)
add = mcp.tool()(_add)
subtract = mcp.tool()(_subtract)
multiply = mcp.tool()(_multiply)
divide = mcp.tool()(_divide)


# ============================================================================
# MAIN - Server startup
# ============================================================================

if __name__ == "__main__":
    # Log server info to stderr (stdout is reserved for MCP protocol)
    print("", file=sys.stderr)
    print("🧮 Calculator MCP Server Starting", file=sys.stderr)
    print("", file=sys.stderr)
    print("📋 Available tools:", file=sys.stderr)
    print("   - add(a, b): Add two numbers", file=sys.stderr)
    print("   - subtract(a, b): Subtract b from a", file=sys.stderr)
    print("   - multiply(a, b): Multiply two numbers", file=sys.stderr)
    print("   - divide(a, b): Divide a by b (handles zero)", file=sys.stderr)
    print("", file=sys.stderr)
    print("💡 Configure in Claude Desktop to use these tools!", file=sys.stderr)
    print("", file=sys.stderr)

    # Run the MCP server
    # This uses stdio transport (standard for Claude Desktop)
    mcp.run()
